# ACM AI Beginner Track
## Walkthrough for the Data Analytics workshop
This document contains all the details of the Data Analytics workshop that need to be shown to students participating in the AI Beginner Track.

**Begin by demonstrating how to import the Numpy and Pandas libraries.**

In [1]:
import numpy as np
import pandas as pd

**Demonstrate how to create a Numpy array. Highlight differences between vectors and matrices.**

In [3]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Creating an array within and over an interval.**

In [16]:
# np.arange(lower_bound, upper_bound, spacing)
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
np.arange(1,10,3)

array([1, 4, 7])

In [17]:
# np.linspace(lower_bound, upper_bound, number_of_values)
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.linspace(1,10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

**Creating an array of random values.**

In [20]:
# Random number between 1 and 10.
np.random.randint(1,10)

3

In [22]:
# Five random numbers between 1 and 10.
np.random.randint(1,10, 5)

array([6, 7, 4, 2, 6])

In [24]:
# Ten random values between 0 inclusive and 1 exclusive.
np.random.rand(10)

array([0.91579902, 0.00192366, 0.46134018, 0.45634536, 0.75895027,
       0.08286168, 0.23453266, 0.56508013, 0.57009967, 0.64946642])

In [28]:
# Ten random values from the standard normal distribution.
np.random.randn(10)

array([ 0.35089016, -0.41316642, -0.40191492, -0.9670939 ,  0.28710696,
       -1.53575363, -0.27459666,  0.56416427, -1.04595812, -0.53421185])

In [33]:
# 5x5 matrix of random values from the standard normal distribution.
np.random.randn(5,5)

array([[-0.78470825, -0.3009308 , -0.97034251,  1.41170743, -0.76681071],
       [ 1.85334106, -0.56161042,  0.60727931, -0.73539151, -0.41463352],
       [-0.26068733,  0.02082152, -0.02376478,  1.60272834, -0.1091803 ],
       [ 1.93477099, -1.00939486, -0.29990982,  0.389838  ,  1.018366  ],
       [-0.7376452 , -1.43321537,  0.62090993, -0.45446043,  0.34033139]])

**Show various Numpy array attributes.**

In [57]:
np_array = np.random.randint(0,99, 100)
np_array

array([47, 62, 94, 37, 88, 30,  8, 48, 75,  9, 93, 64,  9, 54, 15, 38, 69,
       56, 87, 63, 30, 41, 93,  2, 25, 28, 31, 56, 97, 97, 36, 42, 74,  6,
       38, 79,  4, 89, 74, 11, 49, 78, 62, 39,  7, 51, 72,  7, 36, 22, 24,
       93, 31, 27, 29, 39, 71, 75, 44,  4, 66, 62, 31, 75, 82, 76, 65, 81,
       26,  5, 49, 52,  4, 21, 15, 33, 16, 44, 64, 28, 35, 69, 64, 45, 67,
       56, 20, 31, 62, 77, 21, 62,  6, 27, 56, 91,  9, 87, 75, 88])

In [58]:
np_array = np_array.reshape(10,10)
np_array

array([[47, 62, 94, 37, 88, 30,  8, 48, 75,  9],
       [93, 64,  9, 54, 15, 38, 69, 56, 87, 63],
       [30, 41, 93,  2, 25, 28, 31, 56, 97, 97],
       [36, 42, 74,  6, 38, 79,  4, 89, 74, 11],
       [49, 78, 62, 39,  7, 51, 72,  7, 36, 22],
       [24, 93, 31, 27, 29, 39, 71, 75, 44,  4],
       [66, 62, 31, 75, 82, 76, 65, 81, 26,  5],
       [49, 52,  4, 21, 15, 33, 16, 44, 64, 28],
       [35, 69, 64, 45, 67, 56, 20, 31, 62, 77],
       [21, 62,  6, 27, 56, 91,  9, 87, 75, 88]])

In [59]:
np_array.max()

97

In [60]:
np_array.mean()

48.02

In [61]:
np_array.argmin()

23

In [62]:
np_array.shape

(10, 10)

**Demonstrate array selection and broadcasting**

In [63]:
np_array

array([[47, 62, 94, 37, 88, 30,  8, 48, 75,  9],
       [93, 64,  9, 54, 15, 38, 69, 56, 87, 63],
       [30, 41, 93,  2, 25, 28, 31, 56, 97, 97],
       [36, 42, 74,  6, 38, 79,  4, 89, 74, 11],
       [49, 78, 62, 39,  7, 51, 72,  7, 36, 22],
       [24, 93, 31, 27, 29, 39, 71, 75, 44,  4],
       [66, 62, 31, 75, 82, 76, 65, 81, 26,  5],
       [49, 52,  4, 21, 15, 33, 16, 44, 64, 28],
       [35, 69, 64, 45, 67, 56, 20, 31, 62, 77],
       [21, 62,  6, 27, 56, 91,  9, 87, 75, 88]])

In [69]:
np_array[0, 0]

47

In [70]:
np_array[:]

array([[47, 62, 94, 37, 88, 30,  8, 48, 75,  9],
       [93, 64,  9, 54, 15, 38, 69, 56, 87, 63],
       [30, 41, 93,  2, 25, 28, 31, 56, 97, 97],
       [36, 42, 74,  6, 38, 79,  4, 89, 74, 11],
       [49, 78, 62, 39,  7, 51, 72,  7, 36, 22],
       [24, 93, 31, 27, 29, 39, 71, 75, 44,  4],
       [66, 62, 31, 75, 82, 76, 65, 81, 26,  5],
       [49, 52,  4, 21, 15, 33, 16, 44, 64, 28],
       [35, 69, 64, 45, 67, 56, 20, 31, 62, 77],
       [21, 62,  6, 27, 56, 91,  9, 87, 75, 88]])

In [72]:
# Getting values in first 3 rows and columns 3 to 7.
np_array[0:3, 3:7]

array([[37, 88, 30,  8],
       [54, 15, 38, 69],
       [ 2, 25, 28, 31]])

In [74]:
np_array[0,0] = 100
np_array

array([[100,  62,  94,  37,  88,  30,   8,  48,  75,   9],
       [ 93,  64,   9,  54,  15,  38,  69,  56,  87,  63],
       [ 30,  41,  93,   2,  25,  28,  31,  56,  97,  97],
       [ 36,  42,  74,   6,  38,  79,   4,  89,  74,  11],
       [ 49,  78,  62,  39,   7,  51,  72,   7,  36,  22],
       [ 24,  93,  31,  27,  29,  39,  71,  75,  44,   4],
       [ 66,  62,  31,  75,  82,  76,  65,  81,  26,   5],
       [ 49,  52,   4,  21,  15,  33,  16,  44,  64,  28],
       [ 35,  69,  64,  45,  67,  56,  20,  31,  62,  77],
       [ 21,  62,   6,  27,  56,  91,   9,  87,  75,  88]])

In [75]:
np_array_copy = np_array.copy()
np_array_copy[0,0] = 1000

In [76]:
np_array

array([[100,  62,  94,  37,  88,  30,   8,  48,  75,   9],
       [ 93,  64,   9,  54,  15,  38,  69,  56,  87,  63],
       [ 30,  41,  93,   2,  25,  28,  31,  56,  97,  97],
       [ 36,  42,  74,   6,  38,  79,   4,  89,  74,  11],
       [ 49,  78,  62,  39,   7,  51,  72,   7,  36,  22],
       [ 24,  93,  31,  27,  29,  39,  71,  75,  44,   4],
       [ 66,  62,  31,  75,  82,  76,  65,  81,  26,   5],
       [ 49,  52,   4,  21,  15,  33,  16,  44,  64,  28],
       [ 35,  69,  64,  45,  67,  56,  20,  31,  62,  77],
       [ 21,  62,   6,  27,  56,  91,   9,  87,  75,  88]])

In [77]:
np_array_copy

array([[1000,   62,   94,   37,   88,   30,    8,   48,   75,    9],
       [  93,   64,    9,   54,   15,   38,   69,   56,   87,   63],
       [  30,   41,   93,    2,   25,   28,   31,   56,   97,   97],
       [  36,   42,   74,    6,   38,   79,    4,   89,   74,   11],
       [  49,   78,   62,   39,    7,   51,   72,    7,   36,   22],
       [  24,   93,   31,   27,   29,   39,   71,   75,   44,    4],
       [  66,   62,   31,   75,   82,   76,   65,   81,   26,    5],
       [  49,   52,    4,   21,   15,   33,   16,   44,   64,   28],
       [  35,   69,   64,   45,   67,   56,   20,   31,   62,   77],
       [  21,   62,    6,   27,   56,   91,    9,   87,   75,   88]])

In [78]:
np_array > 50

array([[ True,  True,  True, False,  True, False, False, False,  True,
        False],
       [ True,  True, False,  True, False, False,  True,  True,  True,
         True],
       [False, False,  True, False, False, False, False,  True,  True,
         True],
       [False, False,  True, False, False,  True, False,  True,  True,
        False],
       [False,  True,  True, False, False,  True,  True, False, False,
        False],
       [False,  True, False, False, False, False,  True,  True, False,
        False],
       [ True,  True, False,  True,  True,  True,  True,  True, False,
        False],
       [False,  True, False, False, False, False, False, False,  True,
        False],
       [False,  True,  True, False,  True,  True, False, False,  True,
         True],
       [False,  True, False, False,  True,  True, False,  True,  True,
         True]])

In [86]:
np_array[np_array > 50]

array([100,  62,  94,  88,  75,  93,  64,  54,  69,  56,  87,  63,  93,
        56,  97,  97,  74,  79,  89,  74,  78,  62,  51,  72,  93,  71,
        75,  66,  62,  75,  82,  76,  65,  81,  52,  64,  69,  64,  67,
        56,  62,  77,  62,  56,  91,  87,  75,  88])

**Show universal array functions.**

In [87]:
np.exp(np_array)

array([[2.68811714e+43, 8.43835667e+26, 6.66317622e+40, 1.17191424e+16,
        1.65163625e+38, 1.06864746e+13, 2.98095799e+03, 7.01673591e+20,
        3.73324200e+32, 8.10308393e+03],
       [2.45124554e+40, 6.23514908e+27, 8.10308393e+03, 2.83075330e+23,
        3.26901737e+06, 3.18559318e+16, 9.25378173e+29, 2.09165950e+24,
        6.07603023e+37, 2.29378316e+27],
       [1.06864746e+13, 6.39843494e+17, 2.45124554e+40, 7.38905610e+00,
        7.20048993e+10, 1.44625706e+12, 2.90488497e+13, 2.09165950e+24,
        1.33833472e+42, 1.33833472e+42],
       [4.31123155e+15, 1.73927494e+18, 1.37338298e+32, 4.03428793e+02,
        3.18559318e+16, 2.03828107e+34, 5.45981500e+01, 4.48961282e+38,
        1.37338298e+32, 5.98741417e+04],
       [1.90734657e+21, 7.49841700e+33, 8.43835667e+26, 8.65934004e+16,
        1.09663316e+03, 1.40934908e+22, 1.85867175e+31, 1.09663316e+03,
        4.31123155e+15, 3.58491285e+09],
       [2.64891221e+10, 2.45124554e+40, 2.90488497e+13, 5.32048241e+11,
   

In [88]:
np.sin(np_array)

array([[-0.50636564, -0.7391807 , -0.24525199, -0.64353813,  0.0353983 ,
        -0.98803162,  0.98935825, -0.76825466, -0.38778164,  0.41211849],
       [-0.94828214,  0.92002604,  0.41211849, -0.55878905,  0.65028784,
         0.29636858, -0.11478481, -0.521551  , -0.82181784,  0.1673557 ],
       [-0.98803162, -0.15862267, -0.94828214,  0.90929743, -0.13235175,
         0.27090579, -0.40403765, -0.521551  ,  0.37960774,  0.37960774],
       [-0.99177885, -0.91652155, -0.98514626, -0.2794155 ,  0.29636858,
        -0.44411267, -0.7568025 ,  0.86006941, -0.98514626, -0.99999021],
       [-0.95375265,  0.51397846, -0.7391807 ,  0.96379539,  0.6569866 ,
         0.67022918,  0.25382336,  0.6569866 , -0.99177885, -0.00885131],
       [-0.90557836, -0.94828214, -0.40403765,  0.95637593, -0.66363388,
         0.96379539,  0.95105465, -0.38778164,  0.01770193, -0.7568025 ],
       [-0.02655115, -0.7391807 , -0.40403765, -0.38778164,  0.31322878,
         0.56610764,  0.82682868, -0.62988799

**Creating Pandas series.**

In [96]:
# Pandas series have both an index and values.
some_series = pd.Series(data=[1,2,3,4,5], index=['A', 'B', 'C', 'D', 'E'])
some_series

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [97]:
# You can use the index to access values.
some_series['A']

1

In [99]:
# You can also carry out elementwise operations between two series.
another_series = pd.Series(data=[10,20,30,40,50], index=['A', 'B', 'C', 'D', 'E'])

some_series + another_series

A    11
B    22
C    33
D    44
E    55
dtype: int64

**Creating a Pandas Dataframe.**

In [121]:
df = pd.DataFrame(data=np_array, 
                  index=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], 
                  columns=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
df

a   b   c   d   e   f   g   h   i   j
A  100  62  94  37  88  30   8  48  75   9
B   93  64   9  54  15  38  69  56  87  63
C   30  41  93   2  25  28  31  56  97  97
D   36  42  74   6  38  79   4  89  74  11
E   49  78  62  39   7  51  72   7  36  22
F   24  93  31  27  29  39  71  75  44   4
G   66  62  31  75  82  76  65  81  26   5
H   49  52   4  21  15  33  16  44  64  28
I   35  69  64  45  67  56  20  31  62  77
J   21  62   6  27  56  91   9  87  75  88

In [122]:
df['a']

A    100
B     93
C     30
D     36
E     49
F     24
G     66
H     49
I     35
J     21
Name: a, dtype: int64

In [123]:
df['a'].dtype

dtype('int64')

Both columns and rows of a DataFrame are Pandas Series and therefore all the methods discussed before apply.

In [124]:
type(df['a'])

pandas.core.series.Series

In [125]:
df.loc['A']

a    100
b     62
c     94
d     37
e     88
f     30
g      8
h     48
i     75
j      9
Name: A, dtype: int64

In [126]:
type(df.loc['A'])

pandas.core.series.Series

**Adding and removing columns and rows.**

In [127]:
df['z'] = pd.Series(data=np.random.randint(100,999,10), index=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'])
df

a   b   c   d   e   f   g   h   i   j    z
A  100  62  94  37  88  30   8  48  75   9  405
B   93  64   9  54  15  38  69  56  87  63  629
C   30  41  93   2  25  28  31  56  97  97  151
D   36  42  74   6  38  79   4  89  74  11  387
E   49  78  62  39   7  51  72   7  36  22  256
F   24  93  31  27  29  39  71  75  44   4  789
G   66  62  31  75  82  76  65  81  26   5  954
H   49  52   4  21  15  33  16  44  64  28  534
I   35  69  64  45  67  56  20  31  62  77  768
J   21  62   6  27  56  91   9  87  75  88  993

In [136]:
new_row = pd.Series(data=np.random.randint(100,999,11), index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'z'], name='Z')
df = df.append(new_row)
df

a    b    c    d    e    f    g    h    i    j    z
A  100   62   94   37   88   30    8   48   75    9  405
B   93   64    9   54   15   38   69   56   87   63  629
C   30   41   93    2   25   28   31   56   97   97  151
D   36   42   74    6   38   79    4   89   74   11  387
E   49   78   62   39    7   51   72    7   36   22  256
F   24   93   31   27   29   39   71   75   44    4  789
G   66   62   31   75   82   76   65   81   26    5  954
H   49   52    4   21   15   33   16   44   64   28  534
I   35   69   64   45   67   56   20   31   62   77  768
J   21   62    6   27   56   91    9   87   75   88  993
Z  398  474  239  812  527  662  603  270  488  588  485

In [137]:
df.drop('Z', inplace=True)
df

a   b   c   d   e   f   g   h   i   j    z
A  100  62  94  37  88  30   8  48  75   9  405
B   93  64   9  54  15  38  69  56  87  63  629
C   30  41  93   2  25  28  31  56  97  97  151
D   36  42  74   6  38  79   4  89  74  11  387
E   49  78  62  39   7  51  72   7  36  22  256
F   24  93  31  27  29  39  71  75  44   4  789
G   66  62  31  75  82  76  65  81  26   5  954
H   49  52   4  21  15  33  16  44  64  28  534
I   35  69  64  45  67  56  20  31  62  77  768
J   21  62   6  27  56  91   9  87  75  88  993

In [140]:
df.drop('z', inplace=True, axis=1)
df

a   b   c   d   e   f   g   h   i   j
A  100  62  94  37  88  30   8  48  75   9
B   93  64   9  54  15  38  69  56  87  63
C   30  41  93   2  25  28  31  56  97  97
D   36  42  74   6  38  79   4  89  74  11
E   49  78  62  39   7  51  72   7  36  22
F   24  93  31  27  29  39  71  75  44   4
G   66  62  31  75  82  76  65  81  26   5
H   49  52   4  21  15  33  16  44  64  28
I   35  69  64  45  67  56  20  31  62  77
J   21  62   6  27  56  91   9  87  75  88

**Conditionally selecting rows and columns.**

In [142]:
df > 50

a      b      c      d      e      f      g      h      i      j
A   True   True   True  False   True  False  False  False   True  False
B   True   True  False   True  False  False   True   True   True   True
C  False  False   True  False  False  False  False   True   True   True
D  False  False   True  False  False   True  False   True   True  False
E  False   True   True  False  False   True   True  False  False  False
F  False   True  False  False  False  False   True   True  False  False
G   True   True  False   True   True   True   True   True  False  False
H  False   True  False  False  False  False  False  False   True  False
I  False   True   True  False   True   True  False  False   True   True
J  False   True  False  False   True   True  False   True   True   True

In [143]:
df[df > 50]

a     b     c     d     e     f     g     h     i     j
A  100.0  62.0  94.0   NaN  88.0   NaN   NaN   NaN  75.0   NaN
B   93.0  64.0   NaN  54.0   NaN   NaN  69.0  56.0  87.0  63.0
C    NaN   NaN  93.0   NaN   NaN   NaN   NaN  56.0  97.0  97.0
D    NaN   NaN  74.0   NaN   NaN  79.0   NaN  89.0  74.0   NaN
E    NaN  78.0  62.0   NaN   NaN  51.0  72.0   NaN   NaN   NaN
F    NaN  93.0   NaN   NaN   NaN   NaN  71.0  75.0   NaN   NaN
G   66.0  62.0   NaN  75.0  82.0  76.0  65.0  81.0   NaN   NaN
H    NaN  52.0   NaN   NaN   NaN   NaN   NaN   NaN  64.0   NaN
I    NaN  69.0  64.0   NaN  67.0  56.0   NaN   NaN  62.0  77.0
J    NaN  62.0   NaN   NaN  56.0  91.0   NaN  87.0  75.0  88.0

In [148]:
df[df > 50].fillna(':(')

a   b   c   d   e   f   g   h   i   j
A  100  62  94  :(  88  :(  :(  :(  75  :(
B   93  64  :(  54  :(  :(  69  56  87  63
C   :(  :(  93  :(  :(  :(  :(  56  97  97
D   :(  :(  74  :(  :(  79  :(  89  74  :(
E   :(  78  62  :(  :(  51  72  :(  :(  :(
F   :(  93  :(  :(  :(  :(  71  75  :(  :(
G   66  62  :(  75  82  76  65  81  :(  :(
H   :(  52  :(  :(  :(  :(  :(  :(  64  :(
I   :(  69  64  :(  67  56  :(  :(  62  77
J   :(  62  :(  :(  56  91  :(  87  75  88

**Demonstrate how Pandas can be used for exploratory data analysis.**

**Dataset 1**

In [149]:
students = pd.read_csv("Beginner Track - Student Performance Dataset.csv")
students.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [150]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64 
 6   reading score                1000 non-null   int64 
 7   writing score                1000 non-null   int64 
dtypes: int64(3), object(5)
memory usage: 62.6+ KB


In [170]:
# How many male students?
students[students['gender'] == "male"]['gender'].count()

482

In [157]:
# Average math score?
students['math score'].sum()/students['math score'].count()

66.089

In [159]:
# Number of ethnicities.
students['race/ethnicity'].unique()

array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)

In [161]:
students_by_ethnicity = students.groupby('race/ethnicity')
students_by_ethnicity

In [162]:
# Mean scores by ethnicity.
students_by_ethnicity.mean()

math score  reading score  writing score
race/ethnicity                                          
group A          61.629213      64.674157      62.674157
group B          63.452632      67.352632      65.600000
group C          64.463950      69.103448      67.827586
group D          67.362595      70.030534      70.145038
group E          73.821429      73.028571      71.407143

In [191]:
# How many in each ethnicity group had standard lunches?
students_by_ethnicity['lunch'].value_counts()

race/ethnicity  lunch       
group A         standard         53
                free/reduced     36
group B         standard        121
                free/reduced     69
group C         standard        205
                free/reduced    114
group D         standard        167
                free/reduced     95
group E         standard         99
                free/reduced     41
Name: lunch, dtype: int64

In [192]:
# What was the minimum reading score?
students['reading score'].min()

17

In [194]:
# What was the maximum reading score?
students['reading score'].max()

100

In [212]:
# How many students who had standard lunches and were female and got more than a 60 in their reading scores?
students[(students['gender'] == 'female') & (students['lunch'] == 'standard') & (students['reading score'] > 60)]['reading score'].count()

292

**Dataset 2**

In [215]:
salaries = pd.read_csv('Beginner Track - Salaries.csv', index_col = 'Id')
salaries.head()

/Users/adithyanair/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (3,4,5,6,12) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


EmployeeName                                        JobTitle BasePay  \
Id                                                                              
1      NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411   
2        GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)  155966   
3      ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)  212739   
4   CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   77916   
5     PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134402   

   OvertimePay OtherPay Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
Id                                                                           
1            0   400184      NaN  567595.43         567595.43  2011    NaN   
2       245132   137811      NaN  538909.28         538909.28  2011    NaN   
3       106088  16452.6      NaN  335279.91         335279.91  2011    NaN   
4      56120.7   198307      NaN  332343.61         332343.61  2011    NaN   
5         9737   182235      NaN  326373.19         326373.19  2011    NaN   

           Agency Status  
Id                        
1   San Francisco    NaN  
2   San Francisco    NaN  
3   San Francisco    NaN  
4   San Francisco    NaN  
5   San Francisco    NaN

In [214]:
salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148049 non-null  object 
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB


In [226]:
# Checking for removal.
salaries['Benefits'].unique()

array([nan, 44430.12, 69810.19, ..., '0.13', '1.24', 'Not Provided'],
      dtype=object)

In [227]:
# Checking for removal.
salaries['Notes'].unique()

array([nan])

In [228]:
# Checking for removal.
salaries['Status'].unique()

array([nan, 'PT', 'FT'], dtype=object)

In [230]:
salaries.drop('Notes', axis = 1, inplace=True)

In [231]:
salaries

EmployeeName                                        JobTitle  \
Id                                                                          
1          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
2            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
3          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
4       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
5         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148650      Roy I Tillery                                       Custodian   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653       Not provided                                    Not provided   
148654          Joe Lopez                      Counselor, Log Cabin Ranch   

             BasePay   OvertimePay      OtherPay      Benefits   TotalPay  \
Id                                                                          
1             167411             0        400184           NaN  567595.43   
2             155966        245132        137811           NaN  538909.28   
3             212739        106088       16452.6           NaN  335279.91   
4              77916       56120.7        198307           NaN  332343.61   
5             134402          9737        182235           NaN  326373.19   
...              ...           ...           ...           ...        ...   
148650          0.00          0.00          0.00          0.00       0.00   
148651  Not Provided  Not Provided  Not Provided  Not Provided       0.00   
148652  Not Provided  Not Provided  Not Provided  Not Provided       0.00   
148653  Not Provided  Not Provided  Not Provided  Not Provided       0.00   
148654          0.00          0.00       -618.13          0.00    -618.13   

        TotalPayBenefits  Year         Agency Status  
Id                                                    
1              567595.43  2011  San Francisco    NaN  
2              538909.28  2011  San Francisco    NaN  
3              335279.91  2011  San Francisco    NaN  
4              332343.61  2011  San Francisco    NaN  
5              326373.19  2011  San Francisco    NaN  
...                  ...   ...            ...    ...  
148650              0.00  2014  San Francisco     PT  
148651              0.00  2014  San Francisco    NaN  
148652              0.00  2014  San Francisco    NaN  
148653              0.00  2014  San Francisco    NaN  
148654           -618.13  2014  San Francisco     PT  

[148654 rows x 11 columns]

In [237]:
# Who is the highest paid?
salaries[salaries['TotalPayBenefits'] == salaries['TotalPayBenefits'].max()]['EmployeeName']

Id
1    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [240]:
# What are the five most common job titles?
salaries['JobTitle'].value_counts()[0:5]

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

In [241]:
# How many people have the word 'Captain' in their job titles?
salaries['JobTitle'].apply(lambda title: 'Captain' in title).sum()

411